# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac28998231c6b13385fd2db18ab4531753abeb5865f851ef3c212ead47ab180299ac90dd4b45be928cb0516ec9eae0231026ccfa6399a65be6f5d7664bf58b1c

test:
  secret_key_base: 484157fd277fc06ca470c35d48c3c252043397eb1ee9612d7965847af6f578e3c372f4a83495145b5be76c69d4b38bd7e2bf8247f769e231ba311970865c8f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
